# Generated by Django 5.1.1 on 2024-10-20 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drf_app", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="avg_rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="movie",
            name="num_of_ratings",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="drf_app.movie",
            ),
        ),
    ]
