# Generated by Django 5.1.1 on 2024-10-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drf_app", "0003_movie_avg_rating_movie_num_of_ratings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
    ]
